{\rtf1\ansi\ansicpg1252\cocoartf1504\cocoasubrtf830
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl280\partightenfactor0

\f0\fs24 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 name: \cf3 \outl0\strokewidth0 vcor_dual_prf\cf2 \outl0\strokewidth0 \strokec2 \
channels:\
  - conda-forge\
  - defaults\
dependencies:\
  - python=3.7\
  - numpy\
  - scipy\
  - matplotlib\
  - netcdf4\
  - wradlib\
  - cartopy\
  - arm_pyart\
  - xarray\
  - basemap\
  - trmm_rsl}